// Code generated by Kitex v0.7.0. DO NOT EDIT.

package productservice

import (
	product "commerce/idl/product/kitex_gen/product"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SearchProduct(ctx context.Context, Req *product.SearchProductRequest, callOptions ...callopt.Option) (r *product.SearchProductResponse, err error)
	GetProduct(ctx context.Context, Req *product.GetProductRequest, callOptions ...callopt.Option) (r *product.GetProductResponse, err error)
	GetProductList(ctx context.Context, Req *product.GetProductListRequest, callOptions ...callopt.Option) (r *product.GetProductListResponse, err error)
}

// NewClient creates a client for the userservice defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kProductServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the userservice defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kProductServiceClient struct {
	*kClient
}

func (p *kProductServiceClient) SearchProduct(ctx context.Context, Req *product.SearchProductRequest, callOptions ...callopt.Option) (r *product.SearchProductResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchProduct(ctx, Req)
}

func (p *kProductServiceClient) GetProduct(ctx context.Context, Req *product.GetProductRequest, callOptions ...callopt.Option) (r *product.GetProductResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProduct(ctx, Req)
}

func (p *kProductServiceClient) GetProductList(ctx context.Context, Req *product.GetProductListRequest, callOptions ...callopt.Option) (r *product.GetProductListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProductList(ctx, Req)
}
